Чувашов Владислав Максимович

Т120-101М-20

Лабораторная работа по NumPy № 1

 1 Импортировать NumPy под именем np

In [2]:
import numpy as np

2 Напечатать версию и конфигурацию

In [15]:
np.version.full_version

'1.19.2'

In [16]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


3 Создать вектор (одномерный массив) размера 10, заполненный нулями

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4 Создать вектор размера 10, заполненный единицами


In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

5 Создать вектор размера 10, заполненный числом 2.5

In [17]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

6 Как получить документацию о функции numpy.add из командной строки?

In [18]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

7 Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [20]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

8  Создать вектор со значениями от 10 до 49

In [8]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


9 Развернуть вектор (первый становится последним)

In [22]:
np.arange(10,50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

10  Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [24]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

11  Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [27]:
a = np.array([1,2,0,0,4,0])
a.nonzero()


(array([0, 1, 4]),)

12 Создать массив 3x3x3 со случайными значениями

In [53]:
np.random.random((3,3,3))

array([[[0.27041347, 0.15822743, 0.93036714],
        [0.01573616, 0.89474847, 0.15990352],
        [0.90171104, 0.37164251, 0.30556662]],

       [[0.99824488, 0.65711962, 0.55215625],
        [0.19615792, 0.90501024, 0.54121882],
        [0.48524004, 0.7898965 , 0.32310731]],

       [[0.25863251, 0.39244234, 0.30790496],
        [0.60006739, 0.79454275, 0.49755317],
        [0.5194008 , 0.3837123 , 0.53815261]]])

13 Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [67]:
arr = np.random.random((10,10))
print('min = ' + str(arr.min()), 'max = ' + str(arr.max()), sep = '\n')

min = 0.0006500657596492099
max = 0.9973419315560469


14 Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [69]:
arr = np.random.random(30)
print(np.average(arr))

0.47917804051469054


15  Создать матрицу с 0 внутри, и 1 на границах

In [92]:
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

16  Выяснить результат следующих выражений	
    0 * np.nan
    
	np.nan == np.nan
    
	np.inf > np.nan
    
	np.nan - np.nan 

In [93]:
0 * np.nan

nan

In [94]:
np.nan == np.nan

False

In [95]:
np.inf > np.nan

False

In [96]:
np.nan - np.nan 

nan

17 Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [106]:
np.diag(np.arange(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

18  Создать 8x8 матрицу и заполнить её в шахматном порядке

In [119]:
arr = np.zeros((8,8))
arr[::2,::2] = 1
arr[1::2,1::2] = 1
arr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

19  Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [135]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

20 Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [7]:
arr= np.tile(np.array([[0,1],[1,0]]), (4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
